---
title: "Data Exploration"
format:
  closeread-html:
    theme: custom.css
    cr-style:
      narrative-font-size: "24px"
      section-background-color:  #3F704D
      narrative-font-family: 'Poppins'
      narrative-text-color-sidebar: #FDB515
---


To gain a deeper understanding of the parks and neighborhoods included in our analysis, we conducted site visits to several key locations. Experiencing these areas firsthand allowed us to observe the unique atmosphere and characteristics of each neighborhood. Specifically, we visited Saint Anthony Park, Logan Park, Kenwood Park, Lake of the Isles Park, and the Hennepin Energy Recovery Center (HERC). These locations were chosen strategically: Saint Anthony and Logan Parks are situated in neighborhoods with HOLC grades C and D, while Kenwood and Lake of the Isles Park are surrounded by areas with HOLC grades A and B. During these visits, we noted distinct differences in the parks' features and surrounding environments, providing valuable context for our study.

Lake of the Isles park featured bike and walking paths around the lake, docks for fishing, a canoe launch, and a soccer field. The city of Minneapolis completed a large restoration project on the park in 2001 to “create a sustainable as well as usable park space” by restoring the wetlands, improving the lake’s water quality, and reconstructing the recreational paths. To read more about Lake of the isles park, visit https://www.minneapolisparks.org/parks-destinations/parks-lakes/lake_of_the_isles_park/.

Add pics of Lake of the Isles here

Kenwood Park, located directly North of Lake of the Isles, is a hub for outdoor recreational activities. While walking through the park, we saw the many up-to-date amenities including tennis courts, a frisbee golf course, a softball field, a playground, and a picnic area. This park is well funded by the Neighborhood Parks Plan, well maintained, and well attended, making it a model example for urban green space design. To read more about Kenwood Park, visit https://www.minneapolisparks.org/parks-destinations/parks-lakes/kenwood_park/

Add pics of Kenwood Park here

Saint Anthony Park, located in the Saint Anthony East neighborhood of Minneapolis, had a small playground, tennis and basketball courts, a softball field, and an artificial hill. Overall, the amenities at this park were dated and in need of some restoration, however it was promising to see some new trees being planted here. Saint Anthony Park is also funded by the Neighborhood Parks Plan and will continue to be maintained and updated through this program. To read more about Saint Anthony park, visit https://www.minneapolisparks.org/parks-destinations/parks-lakes/st_anthony_park/

Add pics of Saint Anthony Park here

Logan Park is located in the Logan Park neighborhood of Minneapolis. While walking through this park, we saw a cheery birthday celebration going on in the covered picnic area. This park also had some multipurpose athletic fields, a playground, a basketball hoop, and a walking path. The Neighborhood Parks Plan maintains this park and is committed to investing in parks and communities to enhance racial and economic equity. To read more about Logan Park, visit https://www.minneapolisparks.org/parks-destinations/parks-lakes/logan_park/

Add pics of Logan Park

We visited these parks on a Sunday afternoon in late October and concluded that the most noticeable differences in the parks were in quality of amenities and attendance. While we were exploring, Saint Anthony Park seemed empty, gloomy, and industrial compared to the liveliness and social interaction occurring in both Lake of the Isles Park and Kenwood Park. 

Nonetheless, we feel that these green spaces are vital to fostering social connections and enhancing the quality of life for all Minneapolis residents. All of the parks we visited not only served a recreational purpose, but also as a place for community gatherings. From birthday parties, jogging sessions with partners, and local sports team events, all kinds of community building activities were hosted at these parks. It was clear to us that access to well-maintained parks contributes to both physical and mental well-being across Minneapolis. 
